all:
  children:
    sites:
      hosts:
        ec2-3-249-20-210.eu-west-1.compute.amazonaws.com:
          ansible_python_interpreter: /usr/bin/python2
          ansible_port: 22
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'