all:
  children:
    sites:
      hosts:
        ec2-34-253-16-38.eu-west-1.compute.amazonaws.com:
          ansible_python_interpreter: /usr/bin/python3
          ansible_port: 17274
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'