---
- hosts: sites
  remote_user: ubuntu
  tasks:
    - name: Install python3
      apt:
        name: python3
    - name: Install pip3
      apt:
        name: python3-pip
    - name: Install docker python
      pip:
        name: docker
    - name: Pull image
      docker_image:
        name: oisina/alfred:latest
        source: pull
        force: yes
    - name: Remove old
      docker_container:
        name: gideon
        state: absent
    - name: Create container
      docker_container:
        name: alfred
        image: oisina/alfred
        state: started
        network_mode: host
        env:
          ALFRED_TOKEN: "{{ alfred_token }}"
          ALFRED_APPTOKEN: "{{ alfred_apptoken }}"