---
- hosts: sites
  remote_user: ubuntu
  tasks:
    - name: Pull image
      docker_image:
        name: oisina/alfred:main
        source: pull
        force: yes
    - name: Remove old
      docker_container:
        name: alfred
        state: absent
    - name: Create container
      docker_container:
        name: alfred
        image: oisina/alfred:main
        state: started
        network_mode: host
        env:
          ALFRED_TOKEN: "{{ alfred_token }}"
          ALFRED_APPTOKEN: "{{ alfred_apptoken }}"