name: Ansible deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: oisina/alfred
        tag_with_ref: true
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible==2.9.2 requests
    - name: set ansible config secrets
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        mkdir .ssh
        echo "$SSH_KEY" > .ssh/id_rsa
        chmod 600 .ssh/id_rsa
    - name: run exporters playbook
      run: |
        ansible-playbook -i deployment/hosts.yml deployment/playbook.yml --extra-vars="ansible_ssh_private_key_file=.ssh/id_rsa alfred_token=${{ secrets.ALFRED_TOKEN }} alfred_apptoken=${{ secrets.ALFRED_APPTOKEN }}"